#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

from kb import ROOT, _refs, canonical_json, discover_entities, validate_entities


def build(entities):
    nodes = [{"id": e.id, "type": e.type, "path": str(e.path.relative_to(ROOT))} for e in sorted(entities, key=lambda x: x.id)]
    edges = [{"from": e.id, "field": field, "to": ref} for e in entities for field, ref in _refs(e)]
    edges.sort(key=lambda x: (x["from"], x["field"], x["to"]))
    counts = {kind: sum(1 for e in entities if e.type == kind) for kind in ("subject", "source", "event", "claim", "pattern", "measurement")}
    digest = hashlib.sha256(canonical_json({"nodes": nodes, "edges": edges}).encode()).hexdigest()
    return {"schema_version": 1, "content_sha256": digest, "nodes": nodes, "edges": edges}, {"schema_version": 1, "counts": counts}


def coverage_markdown(coverage):
    rows = "\n".join(f"| {kind} | {count} |" for kind, count in coverage["counts"].items())
    return "# Coverage\n\n<!-- generated by tools/build_graph.py; do not edit -->\n\n| Entity | Count |\n|---|---:|\n" + rows + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--root", type=Path, default=None)
    args = parser.parse_args()
    entities = discover_entities(args.root) if args.root else discover_entities()
    errors = validate_entities(entities)
    if errors:
        for error in errors:
            print(f"ERROR {error}", file=sys.stderr)
        return 1
    graph, coverage = build(entities)
    expected = {
        ROOT / "data" / "graph.json": canonical_json(graph),
        ROOT / "data" / "coverage.json": canonical_json(coverage),
        ROOT / "overviews" / "coverage.md": coverage_markdown(coverage),
    }
    if args.root:
        print(f"OK: {len(entities)} entities")
        return 0
    if args.check:
        stale = [path for path, content in expected.items() if not path.exists() or path.read_text(encoding="utf-8") != content]
        if stale:
            for path in stale:
                print(f"ERROR stale generated file: {path.relative_to(ROOT)}", file=sys.stderr)
            return 1
        print(f"OK: {len(entities)} entities; generated files are current")
        return 0
    for path, content in expected.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    print(f"built {len(entities)} entities")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

