#!/usr/bin/env python3
"""Render a readable Subject bundle with observations and inference separated."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

try:
    from build_self_model import (
        ROOT,
        SnapshotError,
        _load_valid_entities,
        build_current_model,
        canonical_json,
        model_path,
        report_stale_artifacts,
        stale_artifacts,
        write_model,
    )
except ModuleNotFoundError:  # Imported as tools.bundle by the test suite.
    from tools.build_self_model import (
        ROOT,
        SnapshotError,
        _load_valid_entities,
        build_current_model,
        canonical_json,
        model_path,
        report_stale_artifacts,
        stale_artifacts,
        write_model,
    )

try:
    from profile_root import (
        ProfileRootError,
        add_profile_root_argument,
        atomic_write_text,
        profile_root_error,
        resolve_profile_root,
    )
except ModuleNotFoundError:  # Imported as tools.bundle by the test suite.
    from tools.profile_root import (
        ProfileRootError,
        add_profile_root_argument,
        atomic_write_text,
        profile_root_error,
        resolve_profile_root,
    )


def bundle_path(subject_id: str, root: Path = ROOT) -> Path:
    kind, slug = subject_id.split("/", 1)
    return root / "data" / "self-models" / kind / f"{slug}.md"


def _display(value: Any) -> str:
    if value is None:
        return "Unknown"
    if isinstance(value, list):
        if not value:
            return "Confirmed empty"
        return "; ".join(_display(item) for item in value)
    if isinstance(value, dict):
        return json.dumps(value, ensure_ascii=False, sort_keys=True)
    return str(value)


def _refs(value: list[str]) -> str:
    return ", ".join(f"`{ref}`" for ref in value) if value else "none"


def _render_observation(observation: dict[str, Any]) -> list[str]:
    context = observation["context"]
    return [
        f"### `{observation['entity_ref']}`",
        f"- Observed facts: {_display(observation['observed_facts'])}",
        f"- Actions: {_display(observation['actions'])}",
        f"- Immediate outcomes: {_display(observation['immediate_outcomes'])}",
        f"- Delayed outcomes: {_display(observation['delayed_outcomes'])}",
        f"- Context: domains={_display(context['domains'])}; social={_display(context['social'])}; uncertainty={_display(context['uncertainty'])}; control={_display(context['control'])}",
        f"- Source refs: {_refs(observation['source_refs'])}",
        "",
    ]


def _render_measurement(measurement: dict[str, Any]) -> list[str]:
    return [
        f"### `{measurement['entity_ref']}`",
        f"- Instrument: {_display(measurement['instrument'])}",
        f"- Administered at: {_display(measurement['administered_at'])}",
        f"- Source refs: {_refs(measurement['source_refs'])}",
        f"- Scores: {_display(measurement['scores'])}",
        f"- Interpretation claim refs: {_refs(measurement['interpretation_claim_refs'])}",
        "",
    ]


def _render_statement(statement: dict[str, Any], *, pattern: bool = False) -> list[str]:
    lines = [
        f"### `{statement['entity_ref']}`",
        f"- Statement: {_display(statement['statement'])}",
        f"- Confidence: {_display(statement['confidence'])}",
        f"- Status: {_display(statement['status'])}",
        f"- Evidence refs: {_refs(statement['evidence_refs'])}",
        f"- Counterevidence refs: {_refs(statement['counterevidence_refs'])}",
    ]
    if pattern:
        lines += [
            f"- Claim refs: {_refs(statement['claim_refs'])}",
            f"- Contexts seen: {_display(statement['contexts_seen'])}",
            f"- Recurring actions: {_display(statement['recurring_actions'])}",
            f"- Recurring drives: {_display(statement['recurring_drives'])}",
        ]
    else:
        lines += [
            f"- Alternatives: {_display(statement['alternative_explanations'])}",
            f"- Supersedes: {_display(statement['supersedes'])}",
            f"- Superseded by: {_display(statement['superseded_by'])}",
        ]
    lines.append("")
    return lines


def _render_derived(statement: dict[str, Any]) -> list[str]:
    lines = [
        f"### `{statement['entity_ref']}`",
        f"- Statement: {_display(statement['statement'])}",
        f"- Confidence: {_display(statement['confidence'])}",
        f"- Status: {_display(statement['status'])}",
        f"- Evidence refs: {_refs(statement['evidence_refs'])}",
        f"- Counterevidence refs: {_refs(statement['counterevidence_refs'])}",
    ]
    if "source_field" in statement:
        lines.append(f"- Source field: `{statement['source_field']}`")
    lines.append("")
    return lines


def render_bundle(model: dict[str, Any]) -> str:
    lines = [
        f"# Self Model Bundle: `{model['subject']}`",
        "",
        "<!-- generated by tools/bundle.py; do not edit -->",
        "",
        "## Snapshot",
        "",
        f"- As of: {_display(model['as_of'])}",
        f"- Source commit: `{model['source_commit']}`",
        f"- Derived from: {_refs(model['derived_from'])}",
        "",
        "## Observations",
        "",
    ]
    observations = model.get("observations", [])
    if observations:
        for observation in observations:
            lines.extend(_render_observation(observation))
    else:
        lines += ["No observations recorded.", ""]

    measurements = model.get("measurements", [])
    if measurements:
        lines += ["### Measurements", ""]
        for measurement in measurements:
            lines.extend(_render_measurement(measurement))

    lines += ["## Inference", ""]
    rendered_claims = False
    for section, title in (
        ("emotions", "Emotions"),
        ("motivations", "Motivations"),
        ("behavioral_principles", "Behavioral principles"),
        ("tensions", "Tensions"),
    ):
        statements = model.get(section, [])
        if not statements:
            continue
        rendered_claims = True
        lines += [f"### {title}", ""]
        for statement in statements:
            lines.extend(_render_statement(statement))
    if model.get("patterns"):
        rendered_claims = True
        lines += ["### Patterns", ""]
        for pattern in model["patterns"]:
            lines.extend(_render_statement(pattern, pattern=True))
    for section, title in (
        ("dominant_triggers", "Dominant triggers"),
        ("dominant_rewards", "Dominant rewards"),
        ("avoidance_targets", "Avoidance targets"),
        ("protective_factors", "Protective factors"),
        ("context_dependencies", "Context dependencies"),
    ):
        lines += [f"### {title}", ""]
        statements = model.get(section, [])
        if statements:
            for statement in statements:
                lines.extend(_render_derived(statement))
        else:
            lines += ["No explicit evidence recorded.", ""]
    if not rendered_claims:
        lines += ["No inferences recorded.", ""]

    lines += ["## Claim history", ""]
    history = model.get("claim_history", [])
    if history:
        for claim in history:
            lines.extend(_render_statement(claim))
    else:
        lines += ["No claims recorded.", ""]

    lines += ["## Unknowns", ""]
    unknowns = model.get("unknowns", [])
    if unknowns:
        for unknown in unknowns:
            field = unknown["field"] or "claim"
            entity_ref = unknown["entity_ref"] or "none"
            lines.append(
                f"- `{unknown['kind']}` field `{field}` entity `{entity_ref}`: {unknown['reason']}; evidence refs: {_refs(unknown['evidence_refs'])}"
            )
    else:
        lines.append("None recorded.")
    lines.append("")
    return "\n".join(lines)


def write_bundle(content: str, path: Path) -> None:
    atomic_write_text(path, content)


def _active_subject_ids(entities) -> list[str]:
    return sorted(
        entity.id
        for entity in entities
        if entity.type == "subject" and entity.meta.get("status") == "active"
    )


def _expected_artifacts(model: dict[str, Any], root: Path = ROOT) -> dict[Path, str]:
    subject_id = model["subject"]
    return {
        model_path(subject_id, root): canonical_json(model),
        bundle_path(subject_id, root): render_bundle(model),
    }


def _build_models(
    entities,
    subject_ids: list[str],
    root: Path = ROOT,
    *,
    source_root: Path = ROOT,
) -> list[dict[str, Any]]:
    return [
        build_current_model(
            entities,
            subject_id,
            root,
            source_root=source_root,
        )
        for subject_id in subject_ids
    ]


def main() -> int:
    parser = argparse.ArgumentParser()
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--subject")
    group.add_argument("--all", action="store_true")
    parser.add_argument("--check", action="store_true")
    add_profile_root_argument(parser)
    args = parser.parse_args()
    if args.profile_root is not None:
        try:
            layout = resolve_profile_root(args.profile_root)
        except ProfileRootError as error:
            profile_root_error(error)
            return 2
        output_root = layout.root
        entity_root = layout.entity_root
    elif args.check:
        output_root = ROOT
        entity_root = ROOT / "entities"
    else:
        profile_root_error(
            ProfileRootError(
                "PROFILE_ROOT_REQUIRED",
                "pass --profile-root for real profile reads and writes; repository fallback is read-only check mode",
            )
        )
        return 2
    entities = _load_valid_entities(root=output_root, entity_root=entity_root)
    subject_ids = _active_subject_ids(entities) if args.all else [args.subject]
    try:
        models = _build_models(entities, subject_ids, output_root, source_root=ROOT)
    except SnapshotError as error:
        print(f"ERROR {error}", file=sys.stderr)
        return 1

    expected = {}
    for model in models:
        expected.update(_expected_artifacts(model, output_root))
    if args.check:
        stale = stale_artifacts(expected)
        if stale:
            command = ".venv/bin/python tools/bundle.py --all" if args.all else f".venv/bin/python tools/bundle.py --subject {args.subject}"
            if args.profile_root:
                command += " --profile-root <external-profile>"
            report_stale_artifacts(stale, command, output_root)
            return 1
        print(f"OK: {len(models)} subject bundle(s) are current")
        return 0

    for model in models:
        write_model(model, model_path(model["subject"], output_root))
        write_bundle(render_bundle(model), bundle_path(model["subject"], output_root))
    print(f"built {len(models)} subject bundle(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
