#!/usr/bin/env python3
"""Render a readable Subject bundle with observations and inference separated."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

try:
    from build_self_model import (
        ROOT,
        _load_valid_entities,
        build_model,
        model_path,
        write_model,
    )
except ModuleNotFoundError:  # Imported as tools.bundle by the test suite.
    from tools.build_self_model import (
        ROOT,
        _load_valid_entities,
        build_model,
        model_path,
        write_model,
    )


def bundle_path(subject_id: str, root: Path = ROOT) -> Path:
    kind, slug = subject_id.split("/", 1)
    return root / "data" / "self-models" / kind / f"{slug}.md"


def _display(value: Any) -> str:
    if value is None:
        return "Unknown"
    if isinstance(value, list):
        if not value:
            return "Confirmed empty"
        return "; ".join(_display(item) for item in value)
    if isinstance(value, dict):
        return json.dumps(value, ensure_ascii=False, sort_keys=True)
    return str(value)


def _refs(value: list[str]) -> str:
    return ", ".join(f"`{ref}`" for ref in value) if value else "none"


def _render_observation(observation: dict[str, Any]) -> list[str]:
    context = observation["context"]
    return [
        f"### `{observation['entity_ref']}`",
        f"- Observed facts: {_display(observation['observed_facts'])}",
        f"- Actions: {_display(observation['actions'])}",
        f"- Immediate outcomes: {_display(observation['immediate_outcomes'])}",
        f"- Delayed outcomes: {_display(observation['delayed_outcomes'])}",
        f"- Context: domains={_display(context['domains'])}; social={_display(context['social'])}; uncertainty={_display(context['uncertainty'])}; control={_display(context['control'])}",
        f"- Source refs: {_refs(observation['source_refs'])}",
        "",
    ]


def _render_measurement(measurement: dict[str, Any]) -> list[str]:
    return [
        f"### `{measurement['entity_ref']}`",
        f"- Instrument: {_display(measurement['instrument'])}",
        f"- Administered at: {_display(measurement['administered_at'])}",
        f"- Source refs: {_refs(measurement['source_refs'])}",
        f"- Scores: {_display(measurement['scores'])}",
        f"- Interpretation claim refs: {_refs(measurement['interpretation_claim_refs'])}",
        "",
    ]


def _render_statement(statement: dict[str, Any], *, pattern: bool = False) -> list[str]:
    lines = [
        f"### `{statement['entity_ref']}`",
        f"- Statement: {_display(statement['statement'])}",
        f"- Confidence: {_display(statement['confidence'])}",
        f"- Status: {_display(statement['status'])}",
        f"- Evidence refs: {_refs(statement['evidence_refs'])}",
        f"- Counterevidence refs: {_refs(statement['counterevidence_refs'])}",
    ]
    if pattern:
        lines += [
            f"- Claim refs: {_refs(statement['claim_refs'])}",
            f"- Contexts seen: {_display(statement['contexts_seen'])}",
            f"- Recurring actions: {_display(statement['recurring_actions'])}",
            f"- Recurring drives: {_display(statement['recurring_drives'])}",
        ]
    else:
        lines += [
            f"- Alternatives: {_display(statement['alternative_explanations'])}",
            f"- Supersedes: {_display(statement['supersedes'])}",
            f"- Superseded by: {_display(statement['superseded_by'])}",
        ]
    lines.append("")
    return lines


def render_bundle(model: dict[str, Any]) -> str:
    lines = [
        f"# Self Model Bundle: `{model['subject']}`",
        "",
        "<!-- generated by tools/bundle.py; do not edit -->",
        "",
        "## Snapshot",
        "",
        f"- As of: {_display(model['as_of'])}",
        f"- Source commit: `{model['source_commit']}`",
        f"- Derived from: {_refs(model['derived_from'])}",
        "",
        "## Observations",
        "",
    ]
    observations = model.get("observations", [])
    if observations:
        for observation in observations:
            lines.extend(_render_observation(observation))
    else:
        lines += ["No observations recorded.", ""]

    measurements = model.get("measurements", [])
    if measurements:
        lines += ["### Measurements", ""]
        for measurement in measurements:
            lines.extend(_render_measurement(measurement))

    lines += ["## Inference", ""]
    rendered_claims = False
    for section, title in (
        ("emotions", "Emotions"),
        ("motivations", "Motivations"),
        ("behavioral_principles", "Behavioral principles"),
        ("tensions", "Tensions"),
    ):
        statements = model.get(section, [])
        if not statements:
            continue
        rendered_claims = True
        lines += [f"### {title}", ""]
        for statement in statements:
            lines.extend(_render_statement(statement))
    if model.get("patterns"):
        rendered_claims = True
        lines += ["### Patterns", ""]
        for pattern in model["patterns"]:
            lines.extend(_render_statement(pattern, pattern=True))
    if not rendered_claims:
        lines += ["No inferences recorded.", ""]

    lines += ["## Claim history", ""]
    history = model.get("claim_history", [])
    if history:
        for claim in history:
            lines.extend(_render_statement(claim))
    else:
        lines += ["No claims recorded.", ""]

    lines += ["## Unknowns", ""]
    unknowns = model.get("unknowns", [])
    if unknowns:
        for unknown in unknowns:
            lines.append(
                f"- `{unknown['entity_ref']}`: {unknown['reason']}; evidence refs: {_refs(unknown['evidence_refs'])}"
            )
    else:
        lines.append("None recorded.")
    lines.append("")
    return "\n".join(lines)


def write_bundle(content: str, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--subject", required=True)
    args = parser.parse_args()
    entities = _load_valid_entities()
    if not any(entity.id == args.subject and entity.type == "subject" for entity in entities):
        raise SystemExit(f"Subject not found: {args.subject}")
    model = build_model(entities, args.subject)
    write_model(model, model_path(args.subject))
    path = bundle_path(args.subject)
    write_bundle(render_bundle(model), path)
    print(f"built {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
